---
x-mariadb-config: &common_config
  image: &common_image mariadb:lts-noble
  environment: &common_env
    MYSQL_ROOT_PASSWORD: password
    TZ: Asia/Seoul
  extra_hosts: &common_hosts
    host.docker.internal: host-gateway
  restart: always

x-mariadb-slave-config: &common_slave_config
  depends_on: master1

services:
  master1: 
    <<: *common_config
    container_name: mariadb-master
    image: *common_image
    ports:
      - 3306:3306
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/conf/my.cnf/:/etc/mysql/my.cnf
      - ./master/sql:/docker-entrypoint-initdb.d
    environment: 
      <<: *common_env
    extra_hosts: 
      <<: *common_hosts

  slave1:
    <<: *common_config
    container_name: mariadb-slave-1
    image: *common_image
    user: 1000:999
    ports:
      - 3307:3306
    volumes: 
      - ./slaves/data/1:/var/lib/mysql
      - ./slaves/conf/1/my.cnf:/etc/mysql/my.cnf
      - ./slaves/sql:/docker-entrypoint-initdb.d
    environment:
      <<: *common_env
    extra_hosts:
      <<: *common_hosts
    depends_on:
      - master1

  slave2:
    container_name: mariadb-slave-2
    image: *common_image
    ports:
      - 3308:3306
    volumes:
      - ./slaves/data/2:/var/lib/mysql
      - ./slaves/conf/2/my.cnf:/etc/mysql/my.cnf
      - ./slaves/sql:/docker-entrypoint-initdb.d
    environment:
      <<: *common_env
    extra_hosts:
      <<: *common_hosts
    depends_on:
      - master1
...