---
services:
  master1: 
    container_name: mariadb-master
    image: mariadb:lts-noble
    ports:
      - 3306:3306
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/conf/my.cnf/:/etc/mysql/my.cnf
      - ./master/sql:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    extra_hosts: 
      host.docker.internal: host-gateway
    restart: always

  slave1:
    container_name: mariadb-slave-1
    image: mariadb:lts-noble
    ports:
      - 3307:3306
    volumes: 
      - ./slaves/data/1:/var/lib/mysql
      - ./slaves/conf/1/my.cnf:/etc/mysql/my.cnf
      - ./slaves/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    extra_hosts:
      host.docker.internal: host-gateway
    restart: always
    depends_on:
      - master1

  slave2:
    container_name: mariadb-slave-2
    image: mariadb:lts-noble
    ports:
      - 3308:3306
    volumes:
      - ./slaves/data/2:/var/lib/mysql
      - ./slaves/conf/2/my.cnf:/etc/mysql/my.cnf
      - ./slaves/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    extra_hosts:
      host.docker.internal: host-gateway
    restart: always
    depends_on:
      - master1
...